name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: larrymargerum01
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#7aa2f7&color_dots=#16161e,#24283b,#414868,#7aa2f7,#bb9af7
            dist/github-contribution-grid-snake-dark.svg?color_snake=#7dcfff&color_dots=#16161e,#24283b,#414868,#7aa2f7,#bb9af7

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          build_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: dist
